### PR TITLE
Enhancements and Optimizations

### PR DESCRIPTION
**Pull request by TurboProgramming**
This PR includes:
- README.md enhanacements.
- New v1.0 release section.
- Assets move to a new "assets" folder.

### CODE REVIEW

**Comment by Nathan2019** [comment]
Sorry to alert you but, I cannot merge due, to a new change in app UI and upcoming changes to themes! I will add the things that do not include or are limited to:
**

Screenshots Of An Older Version Of My App

**
Your suggestion about moving the assets to an assets folder will be taken into consideration!

**Comment by Nathan2019** [comment]
Other things such as updating an outdated README.md will be changed as well as, on the copyright certification ticket, the info on that is not in compliance with an on-going Copyright registration and Regulations for anything forked with/from Modern Calculator! 
copyrightprotected
dmcaprotected

**Comment by Nathan2019** [comment]
Thank you for contributing to Modern Calculator, the code for other platforms will be released!

**Comment by Nathan2019** [comment]
You enhancement has been decided, more will be added soon... The latest APK has not been removed only because, it was not the latest version that I have not yet released! Here's a sweet hint: **If I remove any APK from the files, I may be releasing a newer version that day or that week  :wink:**

**Comment by TurboProgramming** [comment]
Why are you talking about like I'm a stranger?

**Comment by TurboProgramming** [comment]
Go ahead and request changes?

**Comment by Nathan2019** [comment]
Look... The changes you have requested have been made. Screenshots will be added shortly!

**Comment by TurboProgramming** [comment]
I'm talking about "have been made" "added shortly" etc. Aren't you the one adding them? Talk like a single person. You're not Blockly Studio Staff.

**Comment by TurboProgramming** [comment]
Do whatever you want. Closing PR.

**Pull request closed without merging**
